name: 'Prepare workflow'

runs:
  using: "composite"
  steps:
    - name: 'Setup node'
      uses: actions/setup-node@v5
      with:
        node-version: '24.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@dtrw'
    - name: 'Install dependencies'
      run: yarn
      shell: bash
