name: Prepare workflow
description: Prepare workflow for running tests and linting

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v6.0.9
    - name: Setup node # If changing anything here, change it in workflows/release.yml too
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
