name: 'Check PR'

on:
  pull_request

jobs:
  check-pr:
    name: 'Check PR'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 'Install dependencies'
        run: yarn
        # - name: 'Test configs'
        #   run: yarn test
      - name: 'Lint configs'
        run: yarn lint
      - name: 'Verify yarn.lock is deduplicated'
        run: |
          yarn global add yarn-deduplicate
          yarn-deduplicate
          yarn
          git diff --exit-code -s yarn.lock
