name: Check PR

on:
  workflow_call:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [master]

permissions:
  contents: read

env:
  NODE_VERSION: 26.5

jobs:
  check-pr:
    name: Test PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      - name: Setup runtime and dependencies
        uses: pnpm/setup@v1
        with:
          runtime: node@${{ env.NODE_VERSION }}
          cache: true
      - id: test
        name: Test configs
        run: pnpm test
        background: true
      - id: lint
        name: Lint configs
        run: pnpm lint
        background: true
      - wait: [test, lint]
