name: 'Check PR'

on:
  workflow_call:
    inputs:
      skip-deduplication:
        required: false
        type: boolean
  pull_request:
    branches:
      - 'master'

jobs:
  test-pr:
    name: 'Test PR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
      - name: 'Prepare workflow'
        uses: ./.github/actions/prepare
      - name: 'Test configs'
        run: yarn test

  lint-pr:
    name: 'Lint PR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
      - name: 'Prepare workflow'
        uses: ./.github/actions/prepare
      - name: 'Lint configs'
        run: yarn lint

  check-deps:
    name: 'Check deps deduplication'
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip-deduplication }}
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
      - name: 'Prepare workflow'
        uses: ./.github/actions/prepare
      - name: 'Deduplicate dependencies'
        run: |
          yarn global add yarn-deduplicate
          yarn-deduplicate
          yarn
      - name: 'Verify yarn.lock is intact'
        run: git diff --exit-code yarn.lock
