name: 'Make github and npm releases'

on:
  push:
    tags:
      - "v*"

jobs:
  make-release:
    name: 'Make github and npm releases'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dtrw'
      - name: 'Install dependencies'
        run: yarn
      # - name: 'Test configs'
      #   run: yarn test
      - name: 'Lint configs'
        run: yarn lint
      - name: 'Make .d.ts'
        run: yarn make-types
      - name: 'Publish package'
        run: "yarn publish --tag ${{ ((contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta')) && 'next') || 'latest' }} --access public"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: 'Create a github release'
        uses: "marvinpinto/action-automatic-releases@latest"
        # TODO: https://github.com/marvinpinto/actions/pull/642
        # TODO: body/content
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') }}
          automatic_release_tag: "${{ github.ref_name }}"
